# Generated by Django 4.2.6 on 2023-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_price_payment_currency_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe статус'),
        ),
    ]
