# Generated by Django 4.2.6 on 2023-10-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_stripe_id_payment_stripe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновление'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус подписки'),
        ),
    ]
